---
title: "Back-calculation"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.height = 18, fig.width = 12, message = FALSE, warning = FALSE)

```

# Defining functions and packages

```{r base}

# 1. Source functions ----

source("functions/bcalc_freq.R")
source("functions/bcalc_bayes.R")

# 2. Recquired packages ----

library(plyr)
library(dplyr)
library(tidyr)
library(rstan)

# 3. Source models ----

bcalc_stan <- stan_model("./../stan/bcalc.stan")

# 4. Import data ----

data_complete <- read.csv("./../data/coral_reef_fishes_data.csv")

```

# Bayesian back-calculation

```{r}

# 1. Back-calculation for each species ----

options <- unique(select(data_complete, species))

bc_results <- 
lapply(1:nrow(options), purrr::possibly(function(x){
  print(x)
  print(options[x,])
  data <- dplyr::filter(data_complete, species == options[x, "species"], agecap > 1)
  result <- bcalc_bayes(data)
  return(result)
}, otherwise = NA))

bc_results1 <- bc_results[!is.na(bc_results)] %>% 
  lapply(function(x){x$lengths}) %>% 
  plyr::ldply() %>% 
  dplyr::select(-l_q1, -l_q3) %>% 
  rename("agei" = "age", 
         "Li_sp_m" = "l_m",
         "Li_sp_sd" = "l_sd")

# 2. Bayesian Back-calculation for each species and each location ----

options <- unique(select(data_complete, location, species))

bc_results <- 
lapply(1:nrow(options), purrr::possibly(function(x){
  print(x)
  print(options[x,])
  data <- dplyr::filter(data_complete, location == options[x, "location"], 
                               species == options[x, "species"], agecap > 1)
  result <- bcalc_bayes(data)
  return(result)
}, otherwise = NA))

bc_results2 <- bc_results[!is.na(bc_results)] %>% 
  lapply(function(x){x$lengths}) %>% 
  plyr::ldply() %>% 
  dplyr::select(-l_q1, -l_q3) %>% 
  rename("agei" = "age", 
         "Li_sploc_m" = "l_m",
         "Li_sploc_sd" = "l_sd")

# 3. Add R0p and merge data ----

data_complete <- data_complete %>% 
  dplyr::group_by(id) %>% 
  summarize(R0p = radi[which(agei == 0)]) %>% 
  ungroup(.) %>% 
  merge(data_complete, ., by = "id", all.y = TRUE) %>% 
  merge(., bc_results1, by = c("family", "species", "id", "agei"), all.x = TRUE) %>% 
  merge(., bc_results2, by = c("family", "species", "id", "agei"), all.x = TRUE)

# 4. Rename variables following the standards of growth models ----

data_complete <- data_complete %>% 
  rename("Family" = "family",
         "Genus" = "genus",
         "Species" = "species",
         "ID" = "id",
         "Agei" = "agei",
         "Ri" = "radi",
         "Agecpt" = "agecap",
         "Rcpt" = "radcap",
         "Lcpt" = "lencap",
         "L0p" = "l0p",
         "Biomass" = "biomass",
         "Location" = "location",
         "Observer" = "observer") %>% 
  select(Family, Genus, Species, ID, Agei, Ri, Agecpt, Rcpt, Lcpt, L0p, R0p, 
         Li_sp_m, Li_sp_sd, Li_sploc_m, Li_sploc_sd, Biomass, Location, Observer) # Re-order variables

# 5. Export data ----

write.csv(data_complete, 
          "./../data/size_at_age_coral_reef_fishes_data.csv", 
          row.names = FALSE)

```

# Frequentist back-calculation

```{r eval=FALSE, include=FALSE}

# 1. Back-calculation with frequentist method ----

# 1.1 Back-calculation for each species --

data_complete <- ddply(data_complete, .(species), function(x) bcalc_freq(x))

# 1.2 Replacement of Li at age 0 by the value of L0p --

data_complete$li[data_complete$agei == 0] <- data_complete$l0p[data_complete$agei == 0]

```

# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`