---
title: "Exploratory analysis and QAQC"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_caption: yes
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, fig.height = 18, fig.width = 12, message = FALSE, warning = FALSE, fig.align = "center")

```

# Defining functions and packages

```{r base}

# 1. Source functions ----

source("functions/graphical_par.R")
source("functions/theme_graph.R")
source("functions/pred_vbgf.R")

# 2. Required packages ----

library(tidyverse)
library(kableExtra)
library(formattable)
library(rfishbase)
library(readxl)
library(plotly)

# 3. Set theme_graph() as the default ggplot theme ----

theme_set(theme_graph())

# 4. Load data ----

data_complete <- read.csv("./../data/back-calculated-size-at-age_morat-et-al.csv")

```

# 1. Data exploration

## 1.1 Tables

### 1.1.1 Data with back-calc.

```{r}

data_complete %>% 
  filter(!is.na(Li_sp_m)) %>% 
  summarize_at(vars("ID", "Species", "Family"), n_distinct, na.rm = TRUE) %>% 
  bind_rows(data_complete %>%
              summarize_at(vars("ID", "Species", "Family"), n_distinct, na.rm = TRUE), .) %>% 
  mutate(Type = c("All data", "Back-calculated"), .before = 1) %>% 
  kable(., 
        col.names = c("", "Individual", "Species", "Family"), 
        caption = "Table 1. Comparison of numbers of individuals, species and family for the overall dataset and for back-calculated data") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

```

### 1.1.2 Individual by species

```{r}

data_complete %>%
  group_by(Species) %>% 
  summarise(n = length(unique(ID)),
        min_lencap = round(min(Lcpt, na.rm = TRUE), 0),
        max_lencap = round(max(Lcpt, na.rm = TRUE), 0),
        max_age = max(Agei, na.rm = TRUE)) %>% 
  kable(., 
        col.names = c("Species", "n", "Min length (TL, mm)", "Max length (TL, mm)", "Age max (years)"),
        caption = "Table 2. Number of individuals, minimum and maximum total length (mm) and maximum age, by species") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(1, italic = T)

```

### 1.1.3 Individuals by location

```{r}

data_complete %>%
  group_by(Species, Location) %>% 
  summarise(n = length(unique(ID))) %>% 
  pivot_wider(names_from = Location, values_from = n) %>% 
  mutate(Gambiers = cell_spec(Gambiers, "html", color = ifelse(is.na(Gambiers), "white", "#446CB3")),
         Hao = cell_spec(Hao, "html", color = ifelse(is.na(Hao), "white", "#446CB3")),
         Marquesas = cell_spec(Marquesas, "html", color = ifelse(is.na(Marquesas), "white", "#446CB3")),
         Moorea = cell_spec(Moorea, "html", color = ifelse(is.na(Moorea), "white", "#446CB3")),
         Manuae = cell_spec(Manuae, "html", color = ifelse(is.na(Manuae), "white", "#446CB3")),
         Tuamotu = cell_spec(Tuamotu, "html", color = ifelse(is.na(Tuamotu), "white", "#446CB3"))) %>% 
  kable(., 
        format = "html", escape = FALSE,
        caption = "Table 3. Number of individuals of each species by location") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(1, italic = T)

```

### 1.1.4 Number of NA

```{r}

# 1. Number of NA by variable

data_complete %>%
  summarise_all(~(sum(is.na(.)))) %>% 
  t(.) %>% 
  as.data.frame() %>% 
  kable(., col.names = c("NA"), caption = "Table 4. Number of rows with Non-Available (NA) data by variable") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

```

## 1.2 Plot

### 1.2.1 Agei *vs* Ri

```{r fig.width=15, fig.height=40}

ggplot(data_complete, aes(x = Agei, y = Ri)) +
  geom_point(color = col_color_graph, fill = col_fill_graph, size = 1, shape = 21)+
  theme(strip.text.x = element_text(size = 8, face = "italic"),
        strip.background = element_rect(colour = "black", fill = col_facet, size = 1),
        plot.title = element_text(colour = col_color_graph),
        plot.subtitle = element_text(colour = "black")) +
  facet_wrap(~Species, scales = "free", ncol = 5) +
  labs(x = "Age (years)", y = "Radius at age i (mm)", title = "Check for outliers", subtitle = "agei vs radi")

```

### 1.2.2 Agei *vs* Li (sp.)

```{r fig.width=15, fig.height=40}

ggplot(data_complete, aes(x = Agei, y = Li_sp_m)) +
  geom_point(color = col_color_graph, fill = col_fill_graph, size = 1, shape = 21)+
  theme(strip.text.x = element_text(size = 8),
        strip.background = element_rect(colour = "black", fill = col_facet, size = 1),
        plot.title = element_text(colour = col_color_graph),
        plot.subtitle = element_text(colour = "black"),
        strip.text.y = element_text(angle = 360, face = "italic")) +
  facet_grid(Species~Location, scales = "free") +
  labs(x = "Age (years)", y = "Length at age i (mm)", title = "Check for outliers", subtitle = "agei vs li")

```

### 1.2.3 Agei *vs* Li (sp. and loc.)

```{r fig.width=15, fig.height=40}

ggplot(data_complete, aes(x = Agei, y = Li_sploc_m)) +
  geom_point(color = col_color_graph, fill = col_fill_graph, size = 1, shape = 21)+
  theme(strip.text.x = element_text(size = 8),
        strip.background = element_rect(colour = "black", fill = col_facet, size = 1),
        plot.title = element_text(colour = col_color_graph),
        plot.subtitle = element_text(colour = "black"),
        strip.text.y = element_text(angle = 360, face = "italic")) +
  facet_grid(Species~Location, scales = "free") +
  labs(x = "Age (years)", y = "Length at age i (mm)", title = "Check for outliers", subtitle = "agei vs li")

```






# 2. Usual *vs* Back-calculation

```{r fig.height=4, fig.width=6}

# Packages ----

library(brms)
library(modelr)
library(tidybayes)

# 1. VBGF with back-calc data ----

# 1.1 Extract species --

vbgf1 <- data_complete %>%
  filter(Species == "Ostorhinchus apogonoides") %>%
  select(Family, Location, Species, Agei, Li_sp_m) %>%
  unique() %>%
  mutate(Li_sp_m = Li_sp_m/10)

# 1.2 Make the plot --

ggplot(vbgf1) +
  geom_point(aes(x = Agei, y = Li_sp_m, color = Location)) +
  facet_wrap(~Species, scales = "free")

# 1.3 VBGF with Bayesian --

fit1 <- brm(
  bf(Li_sp_m ~ linf * (1 - exp(-k * (Agei - t0))),
     k ~ 1, linf ~ 1, t0 ~ 1,
     nl = TRUE),
  data = vbgf1, family = gaussian(),
  prior = c(
    prior(normal(10, 5), nlpar = "linf"),
    prior(normal(0.5, 0.5), nlpar = "k"),
    prior(normal(0, 1), nlpar = "t0")
  ),
  control = list(adapt_delta = 0.95), iter = 10000, warmup = 5000
)

# 1.4 Get fitted values --

fitted1 <- vbgf1 %>%
  data_grid(Agei = seq_range(Agei, n = 50)) %>%
  add_fitted_draws(fit1) %>% 
  mutate(Type = "Back-calculated")

# 2. VBGF with raw data ----

# 2.1 Extract species --

vbgf2 <- read.csv("./../data/coral_reef_fishes_data.csv") %>% 
  filter(species == "Ostorhinchus apogonoides") %>%
  select(family, location, species, agecap, lencap) %>%
  unique() %>%
  filter(!agecap == 0) %>%
  mutate(lencap = lencap/10)

# 2.2 Make the plot --

ggplot(vbgf2) +
  geom_point(aes(x = agecap, y = lencap, color = location)) +
  facet_wrap(~species, scales = "free") 

# 2.3 VBGF with Bayesian --

fit2 <- brm(
  bf(lencap ~ linf * (1 - exp(-k * (agecap - t0))),
     k ~ 1, linf ~ 1, t0 ~ 1,
     nl = TRUE),
  data = vbgf2, family = gaussian(),
  prior = c(
    prior(normal(10, 5), nlpar = "linf"),
    prior(normal(0.5, 0.5), nlpar = "k"),
    prior(normal(0, 1), nlpar = "t0")
  ),
  control = list(adapt_delta = 0.95), iter = 10000, warmup = 5000
)

# 2.4 Get fitted values --

fitted2 <- vbgf2 %>%
  data_grid(agecap = seq_range(agecap, n = 50)) %>%
  add_fitted_draws(fit2) %>% 
  rename(Agei = agecap) %>% 
  mutate(Type = "Raw")

# 3. Comparisons ----

fitted_all <- bind_rows(fitted1, fitted2)

vbgf_all <- vbgf2 %>% 
  rename(Family = family, Location = location, Species = species, Agei = agecap, Li_sp_m = lencap) %>% 
  mutate(Type = "Raw") %>% 
  bind_rows(., vbgf1 %>% 
                  mutate(Type = "Back-calculated"))

ggplot() +
  stat_lineribbon(data = fitted_all, aes(x = Agei, y = .value, fill = Type, color = Type), alpha = 0.3) +
  geom_point(data = vbgf_all, aes(x = Agei, y = Li_sp_m, fill = Type), color = "black", shape = 21, show.legend = FALSE) +
  facet_wrap(~Species, scales = "free") +
  labs(x = "Age i", y = "Length at age i") +
  guides(colour = guide_legend(override.aes = list(alpha = 1)))

```




# 3. Comparison with literature

## 3.1 Growth curves

```{r fig.width=8, fig.height=15}

# 1. Load and transform literature data ----

vb_litterature <- read_excel("./../data/von-bertalanffy-literature.xlsx", sheet = 1) %>% 
  mutate(Linf = ifelse(Size_unit == "cm", Linf*10, Linf),
         Size_max = ifelse(Size_unit == "cm", Size_max*10, Size_max)) %>% # Convert values of 'Linf' and 'Size_unit' in mm
  select(-Size_unit) %>% 
  mutate(Line = row_number()) %>% 
  group_by(Line) %>% 
  do(pred_vbgf(data = .))

# 2. Make the plot ----

A <- ggplot(data = vb_litterature, aes(x = Agei, y = Li, color = Reference, group = Line)) +
  geom_line(show.legend = FALSE) +
  labs(x = "Age (year)", y = "Length (mm)") +
  facet_wrap(~Genus, scales = "free", ncol = 3) +
  theme(legend.position='none')

# 3. Convert to plotly ----

ggplotly(A)
  
```

## 3.2 Age maximum















# Annex

```{r}

# 1. Extract the characteristics of individual used as otoliths section examples ----

sections_example <- data_complete %>% 
  filter(ID %in% c("GAM18_B006", "AC_LI_MA_03_17_221", "AC_NI_MA_03_17_118", "AC_PY_MA_03_17_009", "MOO18FE167",
                   "GAM18_B112", "CT_MA_MA_03_17_396", "GAM18_A033", "GAM18_A059", "GAM18_B080", # Acanthuridae
                   "OS_AP_MA_03_17_284", "PR_TA_MA_03_17_101", # Apogonidae
                   "OD_NI_MA_03_17_045", "BA_UN_MO_03_16_003", # Balistidae
                   "GAM18_A100", # Chaetodontidae
                   "GAM18_A156", "SA_MI_MA_03_17_128", # Holocentridae
                   "GAM18_B066", "GAM18_A011", "GAM18_A214", # Labridae
                   "GAM18_B105", "GAM18_B093", # Lethrinidae
                   "LU_GI_MA_03_17_058", "GAM18_B099", # Lutjanidae
                   "GAM18_B129", # Mullidae
                   "GAM18_A135", "CE_BI_MO_03_16_002", "GAM18_B056", "GAM18_A162", "DA_AR_MO_03_16_011",
                   "GAM18_A036", "GAM18_A191", "CH_JO_MO_03_16_013", # Pomacentridae
                   "GAM18_A120", "SC_PS_TA_03_16_019", # Scaridae
                   "GAM18_B012", # Scombridae
                   "GAM18_A073", "GAM18_A089", "EP_FA_MA_03_17_027", "H33", "GAM18_A154", "H70", "GAM18_B052", # Serranidae
                   "GAM18_B019", "SI_SP_MO_03_16_008")) %>% # Siganidae
  filter(Agei == 0) %>% 
  select(Family, Species, ID, Agecpt, Lcpt, Location) %>% 
  arrange(Family, Species) %>% 
  mutate(Legend = paste0(row_number(), ". ", Species, " (", Agecpt, " years, ", Lcpt, " mm TL)"))

# 2. Export the txt file needed for the legend of the figure on otoliths sections ----

write.table(paste(sections_example$Legend, collapse = ", "), 
            "./../doc/03_resubmission_scientific-data/legend_fig_otolith_sections.txt", 
            col.names = FALSE, row.names = FALSE)

```

# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`